{% set name = "quantstats" %}
{% set version = "0.0.51" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/QuantStats-{{ version }}.tar.gz
  sha256: 4a86840e287971a5c4e8b9d8d2a65a0c74ffe89206f1a5e7d4d551db7c354866

build:
  number: 0
  noarch: python
  entry_points:
    - sample=sample:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.0.0
    - numpy >=1.16.5
    - pandas >=0.24.0
    - python >=3.6
    - python-dateutil >=2.0
    - scipy >=1.2.0
    - seaborn >=0.9.0
    - tabulate >=0.8.0
    - yfinance >=0.1.63

test:
  imports:
    - quantstats
  commands:
    - pip list
    - pip list | grep -E "{{ name }}\s+{{ version }}.*"
  requires:
    - pip

about:
  home: https://github.com/ranaroussi/quantstats
  summary: Portfolio analytics for quants
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    QuantStats is a Python library that performs portfolio profiling,
     allowing quants and portfolio managers to understand their
     performance better by providing them with in-depth analytics and
     risk metrics.

extra:
  recipe-maintainers:
    - thewchan
