{% set name = "quantstats" %}
{% set version = "0.0.62" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/QuantStats-{{ version }}.tar.gz
  sha256: 64d8fa6284599c70d407debafbbc368b0d03bc67374ffdb4b4a0d19b335ef965

build:
  number: 1
  noarch: python
  entry_points:
    - sample=sample:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base >=3.0.0
    - numpy >=1.16.5
    - pandas >=0.24.0
    - python >={{ python_min }}
    - python-dateutil >=2.0
    - scipy >=1.2.0
    - seaborn >=0.9.0
    - tabulate >=0.8.0
    - yfinance >=0.1.70

    # Not listed but required nevertheless
    - ipython

test:
  imports:
    - quantstats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ranaroussi/quantstats
  summary: Portfolio analytics for quants
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    QuantStats is a Python library that performs portfolio profiling,
     allowing quants and portfolio managers to understand their
     performance better by providing them with in-depth analytics and
     risk metrics.

extra:
  recipe-maintainers:
    - thewchan
