{% set name = "quantstats" %}
{% set version = "0.0.65" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63536df7b71d18a404423dada774a80bbb890e04be95433a4f8dddb1a7b49e70

build:
  number: 0
  noarch: python
  entry_points:
    - sample=sample:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas >=1.5.0,<3.0.0
    - numpy >=1.21.0,<2.0.0
    - seaborn >=0.11.0
    - matplotlib-base >=3.3.0
    - scipy >=1.7.0
    - tabulate >=0.8.9
    - yfinance >=0.2.35
    - python-dateutil >=2.8.0
    - packaging >=20.0
    # Not listed but required nevertheless
    - ipython

test:
  imports:
    - quantstats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ranaroussi/quantstats
  summary: Portfolio analytics for quants
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    QuantStats is a Python library that performs portfolio profiling,
     allowing quants and portfolio managers to understand their
     performance better by providing them with in-depth analytics and
     risk metrics.

extra:
  recipe-maintainers:
    - thewchan
