schema_version: 1

context:
  name: quantstats
  version: "0.0.85"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: f7440e456f7f79a2f9b7c523353d2c71b2756ba2006857b6a4589f7e5f5e13a0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - sample=sample:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - python >=${{ python_min }}
    - pandas >=2.0.0
    - numpy >=1.24.0
    - scipy >=1.11.0
    - matplotlib-base >=3.7.0
    - seaborn >=0.13.0
    - tabulate >=0.9.0
    - yfinance >=0.2.40
    - python-dateutil >=2.8.0

tests:
  - python:
      imports:
        - quantstats
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Portfolio analytics for quants
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    QuantStats is a Python library that performs portfolio profiling,
    allowing quants and portfolio managers to understand their
    performance better by providing them with in-depth analytics and
    risk metrics.


  homepage: https://github.com/ranaroussi/quantstats

extra:
  recipe-maintainers:
    - thewchan
