schema_version: 1

context:
  name: quantstats
  version: "0.0.66"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8dafe2c10efabe77b09f25ca2f8e6d6040a54f698fe80881b984f277f1578bed

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - sample=sample:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - pandas >=1.5.0,<3.0.0
    - numpy >=1.21.0,<2.0.0
    - seaborn >=0.11.0
    - matplotlib-base >=3.3.0
    - scipy >=1.7.0
    - tabulate >=0.8.9
    - yfinance >=0.2.65
    - python-dateutil >=2.8.0
    - packaging >=20.0
    # Not listed but required nevertheless
    - ipython

tests:
  - python:
      imports:
        - quantstats
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Portfolio analytics for quants
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    QuantStats is a Python library that performs portfolio profiling,
    allowing quants and portfolio managers to understand their
    performance better by providing them with in-depth analytics and
    risk metrics.


  homepage: https://github.com/ranaroussi/quantstats

extra:
  recipe-maintainers:
    - thewchan
